coderQuad/New-Grad-Positions

- README.md
> Akuna matata

- README.md
I should've made one PR for both the location and note update. Sorry about that, but I just saw that this is a start date for Winter/Spring 2022.
> Added notes

- README.md
This isn't the 2022 posting for Facebook. Confirmed via a recruiter and they said it opens in August.
> Removed Facebook

- README.md
Adding Microsoft's new grad job application posted earlier today.
> Adding Microsoft SWE New Grad

- README.md
Not sure if it is the newest job opening, but seems like some of my friends in FB have started to offer referrals.
> Update Facebook New Grad Job Opening and Fix Five Rings Link

- README.md
New Grad application was just released
> Adding Duolingo

- README.md
Dropbox position is for Aug - Dec 2021 start date
> Remove Dropbox

- README.md
Although the position says "You have recently completed a Bachelor's or Master’s degree....." the application allows you to choose "Currently studying Bachelor's degree" as an option.
> Add elastic new grad

- README.md
Includes some extraneous whitespace removed by my text editor.
> Add Blend 2022 job post

- README.md
RBI is Restaurant Brands International
;-)
> Add Blackstone, Twilio, Workday, EAB, IXL, Visa, Gem, Indeed, RBI

- README.md
- delete duplicate Twilio
- add note "Must have US Citizenship or Permanent Residency status" to TD
> Delete / Modify entries

- README.md
and... Redfin, UBS, DraftKings, Coursera
BD is Becton Dickinson ;-)
> Add Accenture, BD, Vise, Circle, Jerry, OneTrust, Cadence.. + 4 more

- README.md
PS:
I am the hiring manager of TikTok Frontend US team. You can email me directly if interested.
> Add TikTok to NG jobs.

- README.md
I can't find anything on their careers site either.
> Hubspot link no longer valid

- README.md
They filled all their new grad spots.
> Remove Modern Treasury

- README.md
Added a new grad systems engineering role from Raytheon in Riverdale, Maryland.
> added raytheon opportunity

- README.md
The link included was for a position last year that was filled.  This will get folks to all of the options in the space that are currently active.
> Update for Fidelity for general Technology

- README.md
https://careers.rtx.com/global/en/job/01544342
> Addition of Raytheon

- README.md
Add a strikethrough for Ratheon as the position is now filled and no longer accepting applications.
> Raytheon is filled

- README.md
Feel it will be nice to add data scientist & ML engineer into the job sub-category to encourage people to also post these jobs
> add data scientist & ML engineer to job sub-category

- README.md
> Virtu Financial opening

- README.md
Added the Capital One TDP New Grad position
> Adding Capital One

- README.md
- Added posting from D. E. Shaw
- Added sponsorship info for D. E. Shaw
> Added posting from D. E. Shaw

- README.md
> Crossout Indeed Link

- README.md
Add 3 SWE positions for 3 different companies
> Add P&G, Phillies, and Caterpillar 

- README.md
updated link as it was not reachable
> Close Sunshine

- README.md
> Added posting from SIG

- README.md
Stytch is the platform for user authentication. We make it simple for developers to build complex authentication flows in a matter of minutes. We look for engineers who are excited to think about what to build, not just how to build it, whether that be a new API product, a feature in our developer dashboard, or a new data pipeline.
> Add Stytch

- README.md
Not a full time position
Mentioned in https://github.com/coderQuad/New-Grad-Positions-2023/pull/167#issuecomment-1186773039
> Close Phillies

- .github/pull_request_template.md
Make instructions comments, so people don't forget to remove them. 
No reason to keep them as actual desctoption.
> Make instructions comments

- README.md
Added 1 New Grad Job Link of Capstone.
> Add Capstone

- README.md
> Remove Duplicate Verkada

- README.md
> Close Cisco (Meraki)

- README.md
Link to Audible is no longer up
> Close Audible

- README.md
Hiring team suggested reaching back out in January for new grad positions
> Add Microsoft

- README.md
> Close Disney

- README.md
> Add Aquatic

- README.md
Reverts coderQuad/New-Grad-Positions-2023#238 
#236 already added it
> Revert "Add Neeva"

- README.md
The internship posting was linked by mistake. Changed it to the new grad posting.
> Update Morgan Stanley

- README.md
> Add Quantcast

- README.md
> Close Applied Intuition

- README.md
> Add General Motors

- README.md
> Close Ceridian

- README.md
> Close Google

- README.md
> Add ThoughtSpot

- README.md
> Add SpaceX

- README.md
adding new cat digital job posting
> Add Cat Digital

- README.md
> Close VMWare

- README.md
> Close Qualcomm

- README-2022.md
> Add Scale AI

- README.md
> Add RVO Health

- README.md
> Add Whatnot

- README.md
> Close Levvel

- README.md
> Add BlackRock

- README.md
- Add Western Digital (#324)
- Add Vecna (#323)
- Add Scale AI (#322)
- Close National Instruments (NI) (#321)
- Add RVO Health (#320)
- Add Delta Airlines (#319)
- Add Duolingo (#318)
- Add Sofi (#316)
- Fix Adobe URL (#315)
- Add Bank of America (#314)
- Add Dell Technologies (#312)
- Add Viasat (#311)
- Add Multiply Labs (#310)
- Add Hardware to Optiver (#309)
- Add Zscaler (#306)
- Add Whatnot (#305)
- Add Neuralink (#303)
- Add Gordian (#298)
- Add Textron (#296)
- Add Bank of America (#295)
- Add Rippling (#294)
- Add U.S. Bank (#276)
- Add NetApp (#274)
- Add Ironclad
> Add Ironclad

- README.md
- Add Western Digital (#324)
- Add Vecna (#323)
- Add Scale AI (#322)
- Close National Instruments (NI) (#321)
- Add RVO Health (#320)
- Add Delta Airlines (#319)
- Add Duolingo (#318)
- Add Sofi (#316)
- Fix Adobe URL (#315)
- Add Bank of America (#314)
- Add Dell Technologies (#312)
- Add Viasat (#311)
- Add Multiply Labs (#310)
- Add Hardware to Optiver (#309)
- Add Zscaler (#306)
- Add Whatnot (#305)
- Add Neuralink (#303)
- Add Gordian (#298)
- Add Textron (#296)
- Add Bank of America (#295)
- Add Rippling (#294)
- Add U.S. Bank (#276)
- Add NetApp (#274)
- Add Belvedere Trading
> Add Belvedere Trading

- README.md
- Add Western Digital (#324)
- Add Vecna (#323)
- Add Scale AI (#322)
- Close National Instruments (NI) (#321)
- Add RVO Health (#320)
- Add Delta Airlines (#319)
- Add Duolingo (#318)
- Add Sofi (#316)
- Fix Adobe URL (#315)
- Add Bank of America (#314)
- Add Dell Technologies (#312)
- Add Viasat (#311)
- Add Multiply Labs (#310)
- Add Hardware to Optiver (#309)
- Add Zscaler (#306)
- Add Whatnot (#305)
- Add Neuralink (#303)
- Add Gordian (#298)
- Add Textron (#296)
- Add Bank of America (#295)
- Add Rippling (#294)
- Add U.S. Bank (#276)
- Add NetApp (#274)
- Add FactSet
> Add FactSet

- README.md
- Add Western Digital (#324)
- Add Vecna (#323)
- Add Scale AI (#322)
- Close National Instruments (NI) (#321)
- Add RVO Health (#320)
- Add Delta Airlines (#319)
- Add Duolingo (#318)
- Add Sofi (#316)
- Fix Adobe URL (#315)
- Add Bank of America (#314)
- Add Dell Technologies (#312)
- Add Viasat (#311)
- Add Multiply Labs (#310)
- Add Hardware to Optiver (#309)
- Add Zscaler (#306)
- Add Whatnot (#305)
- Add Neuralink (#303)
- Add Gordian (#298)
- Add Textron (#296)
- Add Bank of America (#295)
- Add Rippling (#294)
- Add U.S. Bank (#276)
- Add NetApp (#274)
- Add Anyscale
> Add Anyscale

- README.md
> Add Deutsche Bank

- README.md
> Add ByteDance

- README.md
> Close Western Digital

- README.md
> Update National Instruments

- README.md
> Add Singularity Data

- README.md
Update Qualcomm with SWE New Grad Position
> Add Qualcomm

- README.md
> Close Alcon

- README.md
> Add Fidelity

- README.md
> Add DoorDash

- README.md
> Add SingleStore

- README.md
> Close hudl

- README.md
> Add New Relic, Inc.

- README.md
**No Visa Sponsorship**
(I have already been rejected for that.)
> Add Mcdonald's

- README.md
> close twillio

- README.md
> Close Comcast

- README.md
Remove duplicate entry(already exist at line 183)
> Fix Singularity Data

- README.md
> Close Capital One

- README.md
> Add Walmart Sam's Club

- README.md
> Close Livermore Labs

- README.md
* Remove Capstone duplicate
* Change special character in U.S. Bank description
* Update Seven Eight Capital links
* Add Seven Eight Capital jobs
> Remove Capstone Duplicate

- README.md
> Close Raytheon Technologies

- README.md
> Close JPMorgan Chase

- README.md
> Close Neeva

- README.md
Headcount is full for the current cycle. Source: Recruiter
> Close Figma

- README.md
> WillowTree unavailable

- README.md
Roblox has closed their New Grad SWE application
> Close Roblox

- README.md
> Close Benchling

- README-2023.md
Update MathWorks to stable URL
> Update MathWorks to stable URL

- README.md
Added 4 companies (SRC Inc., Perpay, Dynatrace, Capgemini)
> Add 4 companies (SRC Inc., Perpay, Dynatrace, Capgemini)

- README.md
> Add MathWorks

- README.md
old mission: College Graduates - Full-Time - Junior Software Engineer (2024)
> Add Old Mission

- README.md
> Remove Optiver, Chicago 
